#!/bin/bash

# symlink this to ~/.docker-fuzzy-search-exec
# ```
#   ln -s $(pwd)/docker-fuzzy-search-exec <abs_path>/.docker-fuzzy-search-exec
# ```
# Custom defaults for "docker exec"
# The command to execute should be outputted to stdout. This is optional, so if nothing is outputted the 'normal'
# defaults will be used.
# Below is an example implementation

# $1 is the name of the docker image to exec into

_command=''

# image name (without version)
case $(docker inspect --format '{{.Config.Image}}' $1 | sed -e 's/:.*$//g') in

  # EXAMPLE: for an image named "custom/mysql", use the command "mysql"
    "registry.gitlab.node-robotics.com/code/release/navigation" \
      | "registry.gitlab.node-robotics.com/code/edge/navigation/ipa_navigation" )

    _command='bash -c "source /opt/node/setup.bash && exec bash"'

esac

echo $_command
unset _command
