################################################################################
# Keybinds
################################################################################

unbind r
bind r source-file ~/.tmux.conf

# Window splitting
bind | split-window -h
bind - split-window -v

# Set pane-switching to be non-repeatable
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Window spawning
# Spawn window and run command
bind-key C-c command-prompt -p "[ command ]" "new-window '%%'"
# Run command directly and view its output in a buffer
bind-key C-r command-prompt -p "[ run ]" "run-shell '%%'"
# Split window and show man page
bind-key m command-prompt -p "[ man page ]" "split-window 'exec man %%'"
# Split window and run command
bind-key C-s command-prompt -p "[ split ]" "split-window -b '%%'"

################################################################################
# Misc
################################################################################
set -g prefix C-b

# Start windows at 1
set -g base-index 1
set-window-option -g pane-base-index 1

# Window title
set -g set-titles on
set -g set-titles-string '#(whoami) @ #h : #S - #W'

# Enable mouse
set -g mouse on

# Don't fuck up vim
set -sg escape-time 0

# 256 colours
set -g default-terminal "screen-256color"

# Border colours
# slightly brighter than xmonad colours to distinguish
set -g pane-border-style 'fg=#4c4846'
#set -g pane-active-border-style 'fg=#A03809'
set -g pane-active-border-style 'fg=cyan' # make border colour different to distinguish from window manager splits

# vi keybinds in copy mode
setw -g mode-keys vi
set -g status-keys vi

bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# # List of plugins
set -g @plugin 'dracula/tmux'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'


# Status bar
set -g @dracula-plugins "git cpu-usage ram-usage battery"
set -g status-justify centre # center align  window list
set -g status-position top
set -g @dracula-show-powerline true
set -g @dracula-show-left-sep 
set -g @dracula-show-left-icon hostname


# Source local config if exists and readable
if "[ -f ~/.tmux.conf.local ]" "source-file ~/.tmux.conf.local"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
run '~/.tmux/plugins/tpm/tpm'
