# bi0's .tmux.conf

################################################################################
# Keybinds
################################################################################
# use ctrl a instead of ctrl b
#unbind C-b
#set -g prefix C-a
unbind l # would be select last, but we want it for pane selection

# Window switching
bind-key a last-window
#bind-key C-d detach
bind-key Space next-window
bind-key C-Space previous-window

# Window spawning
# Spawn window and run command
bind-key C-c command-prompt -p "[ command ]" "new-window '%%'"
# Run command directly and view its output in a buffer
bind-key C-r command-prompt -p "[ run ]" "run-shell '%%'"
# Split window and show man page
bind-key m command-prompt -p "[ man page ]" "split-window 'exec man %%'"
# Split window and run command
bind-key C-s command-prompt -p "[ split ]" "split-window -b '%%'"

# Make prefix work in vim, nested sessions
#bind-key C-a send-prefix
bind-key C-b send-prefix

# reload config
# bind-key C-r source-file ~/.tmux.conf

# Window splitting
bind | split-window -h
bind - split-window -v
# hjkl pane switching
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind 0 select-window -t 10

################################################################################
# Misc
################################################################################

# Start windows at 1
set -g base-index 1
set-window-option -g pane-base-index 1

# Window title
set -g set-titles on
set -g set-titles-string '#(whoami) @ #h : #S - #W'

set -g aggressive-resize on

# 256 colours
set -g default-terminal "screen-256color"

# send xterm escape sequences for function keys
setw -g xterm-keys on

# vi keybinds in copy mode
setw -g mode-keys vi
set -g status-keys vi

#no bell on putty attach
set -ga terminal-overrides ",xterm*:Cr="

# Don't fuck up vim
set -sg escape-time 0

# Message colours
set -g message-style 'bg=black,fg=red,bold'

# Border colours
# slightly brighter than xmonad colours to distinguish
set -g pane-border-style 'fg=#4c4846'
#set -g pane-active-border-style 'fg=#A03809'
set -g pane-active-border-style 'fg=cyan' # make border colour different to distinguish from window manager splits

# Status bar
set -g status-justify centre # center align  window list
set -g status-position top
set -g status-style 'fg=brightblue,bg=black'
set -g window-status-style 'fg=brightblue,bg=black'

setw -g window-status-current-format '#[bg=#4c4846]#[fg=brightred]#I#[fg=brightblack]:#[fg=cyan]#W#[default]'
setw -g window-status-format '#[fg=blue]#I#[fg=brightblack]:#[default]#W#[fg=brightyellow]#F'

set -g status-left '#[fg=brightblack][ #[fg=brightblue]#(whoami) #[fg=green]@ #[fg=brightyellow]#h #[fg=brightblack]: #[fg=brightblue]#S #[fg=brightblack]]#[default]'
set -g status-left-length 60

#set -g status-right '#[fg=brightblack][ #[fg=blue]%b #[fg=cyan]%d#[fg=brightblack], #[fg=cyan]%H#[fg=brightblack]:#[fg=cyan]%M #[fg=brightblack]]'
#load average monstrosity
if "uname | grep -q OpenBSD" \
	"set -g status-right '#[fg=brightblack][ #[fg=blue]l#[fg=green]:#[fg=cyan]#(sysctl vm.loadavg | cut -d= -f2 | cut -d\\  -f1 | sed -es/\\\\./#[fg=green].#[fg=cyan]/g)#[fg=green], #[fg=cyan]#(sysctl hw.sensors.cpu0.temp0 | cut -d= -f2 | cut -d. -f1)#[fg=blue]°C #[fg=brightblack]| #[fg=blue]%b #[fg=cyan]%d#[fg=green], #[fg=cyan]%H#[fg=green]:#[fg=cyan]%M #[fg=brightblack]]'"\
	"set -g status-right '#[fg=brightblack][ #[fg=blue]l#[fg=green]:#[fg=cyan]#(cat /proc/loadavg | cut -d\\  -f1 | sed -es/\\\\./#[fg=green].#[fg=cyan]/g) #[fg=cyan]#(cat /sys/class/thermal/thermal_zone0/temp | cut -b 1,2)#[fg=blue]°C #[fg=blue]%b #[fg=cyan]%d#[fg=brightblack], #[fg=cyan]%H#[fg=brightblack]:#[fg=cyan]%M #[fg=brightblack]]'"


# Source local config if exists and readable
if "[ -f ~/.tmux.conf.local ]" "source-file ~/.tmux.conf.local"
