# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock

input-field {
  monitor =
  fade_on_empty = false
  # hide_input = true
}

background {
  monitor =
  path = /home/felix/config/images/lockscreen_bw.jpg
}
