MOUSE_BTN3		add volume 2
MOUSE_BTN4		add volume -2
MOUSE_BTN5		seek 10
MOUSE_BTN6		seek -10
UP            add volume 2
DOWN          add volume -2
SHIFT+RIGHT   seek 600
SHIFT+LEFT    seek -600
#ENTER         playlist-next; script-message osc-message "${playlist-pos}/${playlist-count}" 1
SHIFT+ENTER         playlist-prev
>             playlist-next; script-message osc-message "${playlist-pos}/${playlist-count}" 1
<             playlist-prev; script-message osc-message "${playlist-pos}/${playlist-count}" 1
