# OSC settings
script-opts=osc-layout=bottombar,osc-timetotal=no,osc-minmousemove=0,osc-seekbarstyle=bar,osc-hidetimeout=200,osc-fadeduration=200,osc-vidscale=yes

video-sync=display-resample

screenshot-directory=~/Pictures/screenshots/mpv/
screenshot-template="mpv-%f-%p-%n"
[default]
#profile=gpu-hq
#profile=opengl-hq
vo=gpu
#hwdec=vdpau

# General
keep-open=always #don't close player at end of file
no-border

image-display-duration=inf

[extension.png]
video-aspect-override=no

[extension.jpg]
video-aspect-override=no

[extension.jpeg]
video-aspect-override=no

[extension.flac]
keep-open=no

[extension.mp3]
keep-open=no
