resolver: lts-21.24
flags:
  xmobar:
    with_xrender: true
    with_xpm: true
    with_mpd: true
    with_alsa: true
  xmonad-contrib:
    use_xft: true

packages:
  - xmonad/
  - xmonad-contrib/
  - xmobar
  - xmo-config

ghc-options:
  xmonad-contrib: '-j'
  xmobar: '-j'

extra-deps:
  - libmpd-0.10.0.1
  - alsa-mixer-0.3.0.1

allow-newer: true
