#!/bin/bash

setxkbmap -option caps:escape_shifted_capslock

stalonetrayrc="${HOME}/config/xmonad/hosts/$(hostname --short)/stalonetrayrc"
if [ ! -e "${stalonetrayrc}" ]; then
	stalonetrayrc="${HOME}/config/xmonad/stalonetrayrc"
fi
if [ -z "$(pgrep stalonetray)" ]; then
	stalonetray -c "${stalonetrayrc}" &
else
	pkill stalonetray
	stalonetray -c "${stalonetrayrc}" &
fi

pgrep '^nm-applet$' || nm-applet&

pgrep '^gammastep$' || gammastep&

pgrep picom || picom --config ~/config/xmonad/picom.conf &

# presentation mode indicator for xmobar
~/config/scripts/pres_mode init

pkill -USR1 '^gammastep$'
sleep 1
# toggle gammastep twice to update the icon
pkill -USR1 '^gammastep$'

# app launcher
#pgrep kupfer || kupfer --no-splash &

# Single screen
#feh --bg-scale ~/Pictures/Wallpaper\ Switching/IMG_1265-2-2.jpg&

# Multiple screens
sh -c 'sleep 3 && ~/config/scripts/set_multi_wallpapers.sh'
