#!/bin/sh
# 💻🖵 ✓ ❌ ✔ 🗔 📽󰐯
# Nerdfont version
[ "$(xfconf-query  -c xfce4-power-manager -p /xfce4-power-manager/presentation-mode -v)" = "true" ] && echo "󰹑  " ||  echo "󰹑  "
# [ "$(xfconf-query  -c xfce4-power-manager -p /xfce4-power-manager/presentation-mode -v)" = "true" ] && echo "來冷" ||  echo ""
