#!/bin/sh
case $1 in
  'init')
    mkfifo ~/.local/state/presmode 2>/dev/null || true
    ;;
  'toggle')
    xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/presentation-mode -T
    ;;
esac
if [ "$(xfconf-query  -c xfce4-power-manager -p /xfce4-power-manager/presentation-mode -v)" = "true" ]; then
  echo "󰹑  " > ~/.local/state/presmode
else
  echo "󰹑  " > ~/.local/state/presmode
fi
